version = 0.1
[default.deploy.parameters]
stack_name = "todo-crud"
resolve_s3 = true
s3_prefix = "todo-crud"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
